name: Trigger Update Pluginmaster

on:
  release:
    types: [published,unpublished,created,edited,deleted,prereleased,released]
  workflow_dispatch:
  workflow_call:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          # Set the required variables
          repo_owner="NightmareXIV" 
          repo_name="MyDalamudPlugins"  
          event_type="TriggerUpdatePluginmaster" 
  
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.NIGHTMAREXIVWRITEKEY }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"unit\": false, \"integration\": true}}"
